# Generated by Django 2.1.7 on 2019-04-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('unused', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
